{"uuid": "212e0d69-ab7d-4860-878d-37990524821f", "children": ["140a133f-fac0-4d4f-88c2-b1b098f95631"], "befores": [{"name": "login_new_user", "status": "broken", "statusDetails": {"message": "Exception: Не удалось зарегистрировать пользователя и получить токены.\n", "trace": "  File \"C:\\Users\\user\\PycharmProjects\\Diplom_3\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\user\\PycharmProjects\\Diplom_3\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\user\\PycharmProjects\\Diplom_3\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\PycharmProjects\\Diplom_3\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\PycharmProjects\\Diplom_3\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\PycharmProjects\\Diplom_3\\conftest.py\", line 47, in login_new_user\n    raise Exception(\"Не удалось зарегистрировать пользователя и получить токены.\")\n"}, "steps": [{"name": "Регистрация и авторизация нового пользователя через API, возвращение авторизационных данных", "status": "passed", "steps": [{"name": "Генерация данных пользователя", "status": "passed", "start": 1730368630828, "stop": 1730368630830}], "start": 1730368630828, "stop": 1730368631292}], "start": 1730368630828, "stop": 1730368631292}], "start": 1730368630828, "stop": 1730368631319}